### PR TITLE
Fix starting of bricks

### LINKED ISSUE #150: RUNDIR/gluster and LOGDIR/glusterfs/bricks need to be created to start bricks
Bricks fail to start because the above paths are missing.

### PR DESCRIPTION
**Pull request by prashanthpai**
* Create dirs required by brick processes
* Update brick start args
* Wait a little before checking if daemon is up

Closes #150

### CODE REVIEW

**Comment by prashanthpai** [comment]
Don't merge this yet.

**Comment by prashanthpai** [comment]
With PR #189 and #190, bricks are now able to come up.

File: daemon/daemon.go [hunk 1]
```diff
@@ -83,20 +86,23 @@ func Start(d Daemon, wait bool) error {
...
+
+	// It is assumed that the child (or grandchild) has written to pidfile
+	pid, err = ReadPidFromFile(d.PidFile())
 	if err != nil {
 		return err
 	}
 
 	log.WithFields(log.Fields{
 		"name": d.Name(),
-		"pid":  cmd.Process.Pid,
```
Comment (prashanthpai) [inline daemon/daemon.go]: Using `cmd.Process.Pid` is incorrect as actual brick is grandchild of this process.
