### PR TITLE
Tracing: Trace volume option set command.

### LINKED ISSUE #1299: Tracing: Trace volume option set command.
Add instrumentation to trace the volume option set command. Add relevant metadata to the spans like request-id, volume name and the options being set along with the new values.

### Observed behavior
NA

### Expected/desired behavior
Tracing UI should show the high level steps and the time taken for each of the steps. The top level
span must also show the requestID, volume name and the options being set along with new values as part of the request on the tracing UI.

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): master
- Operating system used: fedora27
- Glusterd2 compiled from sources, as a package (rpm/deb), or container: source
- Using External ETCD: (yes/no, if yes ETCD version): no
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 

### Other useful information

- glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
- glusterd2 log files from all nodes (default /var/log/glusterd2/glusterd2.log)
- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

### PR DESCRIPTION
**Pull request by sseshasa**
Add instrumentation to trace volume option set transaction. Add relevant
attributes to the trace like request ID, volume name and the options along
with the values to be set on the volume. This is to help in debugging in
case the command fails for some reason. The instrumentation to trace steps
of this transaction is already in place in the common transaction and
steps framework code.

Closes  #1299

### CODE REVIEW

File: glusterd2/commands/volumes/volume-option.go [hunk 1]
```diff
@@ -262,6 +265,18 @@ func volumeOptionsHandler(w http.ResponseWriter, r *http.Request) {
 		return
 	}
 
+	// Add relevant attributes to the span
+	var optionToSet string
+	for option, value := range req.Options {
+		optionToSet += option + "=" + value + ":"
```
Comment (Madhu-1) [inline glusterd2/commands/volumes/volume-option.go]: question:
is it good to separate options by comma other than colon?

Comment (sseshasa) [reply glusterd2/commands/volumes/volume-option.go]: Earlier I was just including the option name and so I chose colon so that distinguishing the dots in the option name from the comma separator might be a bit difficult. But since I also include the value now, I guess comma should be fine. I will change it.
