### PR TITLE
etcd: session lease expires if there is reconnection to etcd server

### LINKED ISSUE #1054: Stop and Start of External etcd causes to incorrect peer status
-> I have prepared 30  node glusterd2 cluster
-> Single external etcd running from different node not from any one the 30 node cluster
-> if i stop the external etcd wait for some time and start the external etcd
-> if i perform the peer status , all nodes peer status showing offline
-> But still i am able to perform glustercli commands on that node which is offline
For example out put of peer status from one node , that node peer status showing offline, but still i am able to perform peer status from that node

```[root@dhcp42-199 ~]# glustercli peer status
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+-----+
|                  ID                  |               NAME                |  CLIENT ADDRESSES  |   PEER ADDRESSES   | ONLINE | PID |
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+-----+
| 06f72798-01a7-4327-a472-e360f52868c1 | dhcp42-199.lab.eng.blr.redhat.com | 127.0.0.1:24007    | 10.70.42.199:24008 | no     |     |
|                                      |                                   | 10.70.42.199:24007 |                    |        |     |
| 0ce3b780-6ca4-4a0f-9194-27d96cb2b8d9 | dhcp43-189.lab.eng.blr.redhat.com | 127.0.0.1:24007    | 10.70.43.189:24008 | no     |     |
|                                      |                                   | 10.70.43.189:24007 |                    |        |     |
| 121e2b82-6af2-40b2-9af0-6cba5a7d91dd | dhcp43-141.lab.eng.blr.redhat.com | 127.0.0.1:24007    | 10.70.43.141:24008 | no     |     |
|                                      |                                   | 10.70.43.141:24007 |                    |        |     |
| 1ba8d6d2-526a-4444-a737-12f94e5b7e3b | dhcp41-224.lab.eng.blr.redhat.com | 127.0.0.1:24007    | 10.70.41.224:24008 | no     |     |
|                                      |                                   | 10.70.41.224:24007 |                    |        |     |
| 22e8a829-d992-4a27-a259-cba75c013ece | dhcp42-213.lab.eng.blr.redhat.com | 127.0.0.1:24007    | 10.70.42.213:24008 | no     |     |
```

if you observer above peer status command 
I have ran the peer status command from 10.70.42.199, in peer status output 10.70.42.199 showing as offline, 

please let me know which logs i need to provide ??

### PR DESCRIPTION
**Pull request by oshankkumar**
If etcd goes down and comes up then existing session lease
will not be refreshed and expires after lease ttl duration.

This closes #1054

Signed-off-by: Oshank Kumar <okumar@redhat.com>

### CODE REVIEW

**Comment by aravindavk** [comment]
add to whitelist

**Comment by aravindavk** [comment]
Tested it and looks good. Will do the PR review later today.

- Run peer status to see all peers online
- Stop etcd using `systemctl stop etcd`
- Sleep for 10 mins `sleep 600`
- Start etcd again to see it connects back `systemctl start etcd`
- Run peer status to see all peers online again

**Comment by oshankkumar** [comment]
retest this please

**Comment by aravindavk** [comment]
@kshlm any comments on this PR?

File: glusterd2/store/store.go [hunk 1]
```diff
@@ -111,9 +113,65 @@ func New(conf *Config) (*GDStore, error) {
...
+
+	defer ticker.Stop()
+
+	for {
+		select {
+		case <-s.stop:
+			return
+		case <-ticker.C:
+			ctx, cancel := context.WithTimeout(context.Background(), getTimeout*time.Second)
+			defer cancel()
```
Comment (Madhu-1) [inline glusterd2/store/store.go]: are you sure will this defer gets called inside infinite for loop?

Comment (oshankkumar) [reply glusterd2/store/store.go]: @Madhu-1 defer will get called after control came out of the loop, i.e when GDstore will get closed,
but since the context object (ctx) get used at only one place so I have removed the defer.
