### PR TITLE
validate volume name

### LINKED ISSUE #772: creation of volume with  special characters in volume name (except underscore and hyphen) should fail

### PR DESCRIPTION
**Pull request by Madhu-1**
It is necessary to validate volume name before volume creation.
Fixes #772 
Signed-off-by: Madhu Rajanna <mrajanna@redhat.com>

### CODE REVIEW

File: glusterd2/commands/volumes/volume-create.go [hunk 1]
```diff
@@ -17,6 +18,12 @@ import (
 )
 
 func validateVolCreateReq(req *api.VolCreateReq) error {
+	reg := regexp.MustCompile("^[a-zA-Z0-9_-]+$")
```
Comment (aravindavk) [inline glusterd2/commands/volumes/volume-create.go]: Move this to global scope, outside this function

Comment (Madhu-1) [reply glusterd2/commands/volumes/volume-create.go]: done
