### PR TITLE
Tracing: Trace volume delete operation

### LINKED ISSUE #1202: Tracing: Trace "volume delete" command
Add instrumentation to trace volume delete operation. Add the requestID  and volume name as an attribute in the top level span of the trace.

### Observed behavior
NA

### Expected/desired behavior
Tracing UI should show the high level steps and the time taken for each of the steps. The top level
span must also show the requestID and volume name as part of the request on the tracing UI.

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): master
- Operating system used: fedora 27
- Glusterd2 compiled from sources, as a package (rpm/deb), or container: source
- Using External ETCD: (yes/no, if yes ETCD version):no
- If container, which container image: no
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 

### Other useful information

- glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
- glusterd2 log files from all nodes (default /var/log/glusterd2/glusterd2.log)
- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

### PR DESCRIPTION
**Pull request by sseshasa**
Add instrumentation to trace volume delete operation. Add the requestID
and volume name as an attribute in the top level span of the trace.

Closes #1202

### CODE REVIEW

File: glusterd2/commands/volumes/volume-delete.go [hunk 1]
```diff
@@ -45,6 +49,14 @@ func volumeDeleteHandler(w http.ResponseWriter, r *http.Request) {
 	logger := gdctx.GetReqLogger(ctx)
 	volname := mux.Vars(r)["volname"]
 
+	fnName := "?"
+	if pc, _, _, ok := runtime.Caller(0); ok {
```
Comment (Madhu-1) [inline glusterd2/commands/volumes/volume-delete.go]: can we move this function to utils and use this function elsewhere

Comment (sseshasa) [reply glusterd2/commands/volumes/volume-delete.go]: Do you mean factor out this chunk to utils?

	fnName := "?"
	if pc, _, _, ok := runtime.Caller(0); ok {
		fn := runtime.FuncForPC(pc)
		fnName = filepath.Base(fn.Name())
	}

Comment (Madhu-1) [reply glusterd2/commands/volumes/volume-delete.go]: yes, because I see we are using this function in most of the places, 
to avoid code duplication I prefer moving this function to a utils package
