### PR TITLE
Fixed panic caused by stopping liveness watcher

### LINKED ISSUE #1012: gd2 crash while detaching and attaching a peer (external etcd)
Setup:

Two servers, with external etcd running on both of them. The etcd configuration looks like:

```
data-dir: "/var/lib/etcd"
listen-peer-urls: http://10.70.41.250:2380
listen-client-urls: http://10.70.41.250:2379
name: "glusterd2"
initial-advertise-peer-urls: http://10.70.41.250:2380
advertise-client-urls: http://10.70.41.250:2379
```

glusterd2 is started on both the servers, with each server pointing to etcd on it. The gd2 configuration looks like:

```
localstatedir = "/usr/local/var/lib/glusterd2"
logdir = "/usr/local/var/log/glusterd2"
logfile = "glusterd2.log"
loglevel = "INFO"
rundir = "/usr/local/var/run/glusterd2"
defaultpeerport = "24008"
peeraddress = ":24008"
clientaddress = ":24007"
etcdendpoints="http://10.70.41.250:2379"
noembed = true
resauth = true
```

When the run the steps:

1. peer add
2. peer list
3. peer remove
4. peer add

glusterd2 crashes with message

```
2018-07-13 15:17:39.879921 I | etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:2379: connect: connection refused"; Reconnecting to {localhost:2379 <nil>}                                                     
2018-07-13 15:17:40.878899 I | etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:2379: connect: connection refused"; Reconnecting to {localhost:2379 <nil>}                                                     
2018-07-13 15:17:42.567411 I | etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:2379: connect: connection refused"; Reconnecting to {localhost:2379 <nil>}                                                     
2018-07-13 15:17:44.877285 I | etcdserver/api/v3rpc: Failed to dial localhost:2379: context canceled; please retry.                                 

panic: close of closed channel

goroutine 226 [running]:
github.com/gluster/glusterd2/glusterd2/events.stopLivenessWatcher()
        /home/sac/work/golang/src/github.com/gluster/glusterd2/glusterd2/events/liveness.go:77 +0x30                                                
github.com/gluster/glusterd2/glusterd2/events.Stop(0xc4200178d0, 0x1)
        /home/sac/work/golang/src/github.com/gluster/glusterd2/glusterd2/events/events.go:51 +0x22                                                  
github.com/gluster/glusterd2/glusterd2/commands/peers.ReconfigureStore(0xc420195a40, 0x0, 0x0)                                                      
        /home/sac/work/golang/src/github.com/gluster/glusterd2/glusterd2/commands/peers/peer-rpc-svc.go:161 +0x8b                                   
github.com/gluster/glusterd2/glusterd2/commands/peers.(*PeerService).Join(0xc4200b9e68, 0x10b9180, 0xc42090cb70, 0xc42090cc00, 0x0, 0x0, 0x0)       
        /home/sac/work/golang/src/github.com/gluster/glusterd2/glusterd2/commands/peers/peer-rpc-svc.go:83 +0x3b6                                   
github.com/gluster/glusterd2/glusterd2/commands/peers._PeerService_Join_Handler(0xe94ac0, 0xc4200b9e68, 0x10b9180, 0xc42090cb70, 0xc42070e730, 0x0, 0x0, 0x0, 0x7f6ed689a300, 0x0)
        /home/sac/work/golang/src/github.com/gluster/glusterd2/glusterd2/commands/peers/peer-rpc.pb.go:209 +0x241                                   
github.com/gluster/glusterd2/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4206b20c0, 0x10bf160, 0xc4207ffef0, 0xc4206b6ff0, 0xc42090d590, 0x17d4260, 0xc42090cb40, 0x0, 0x0)
        /home/sac/work/golang/src/github.com/gluster/glusterd2/vendor/google.golang.org/grpc/server.go:638 +0x8f3                                   
github.com/gluster/glusterd2/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4206b20c0, 0x10bf160, 0xc4207ffef0, 0xc4206b6ff0, 0xc42090cb40)
        /home/sac/work/golang/src/github.com/gluster/glusterd2/vendor/google.golang.org/grpc/server.go:796 +0x1052                                  
github.com/gluster/glusterd2/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420805420, 0xc4206b20c0, 0x10bf160, 0xc4207ffef0, 0xc4206b6ff0)
        /home/sac/work/golang/src/github.com/gluster/glusterd2/vendor/google.golang.org/grpc/server.go:449 +0x9f                                    
created by github.com/gluster/glusterd2/vendor/google.golang.org/grpc.(*Server).serveStreams.func1                                                  
        /home/sac/work/golang/src/github.com/gluster/glusterd2/vendor/google.golang.org/grpc/server.go:447 +0xa1                                    
[root@dhcp43-250 build]#
```

Attaching logs.
[server1.log](https://github.com/gluster/glusterd2/files/2192367/server1.log)
[server2.log](https://github.com/gluster/glusterd2/files/2192368/server2.log)

### LINKED ISSUE #1092: adding peer followed by removal of same peer cause panic
# Command Executed
[okumar@localhost glusterd2]$ ./build/glustercli --endpoints=http://192.168.122.42:24007 peer list
+--------------------------------------+--------------+-----------------------+-----------------------+--------+------+
|                  ID                  |     NAME     |   CLIENT ADDRESSES    |    PEER ADDRESSES     | ONLINE | PID  |
+--------------------------------------+--------------+-----------------------+-----------------------+--------+------+
| 2f0bfdac-fceb-459a-8939-689da17de77e | gd21.example | 127.0.0.1:24007       | 192.168.122.6:24008   | yes    | 2156 |
|                                      |              | 192.168.122.6:24007   |                       |        |      |
| 854e037e-da80-4ee0-82b8-9ecdb8fc13de | gd22.example | 127.0.0.1:24007       | 192.168.122.42:24008  | yes    | 2563 |
|                                      |              | 192.168.122.42:24007  |                       |        |      |
| a35e9c07-fc7c-45ac-a0a3-4e09869b30ca | gd20.example | 127.0.0.1:24007       | 192.168.122.253:24008 | yes    | 2586 |
|                                      |              | 192.168.122.253:24007 |                       |        |      |
+--------------------------------------+--------------+-----------------------+-----------------------+--------+------+
./build/glustercli --endpoints=http://192.168.122.42:24007 peer remove 2f0bfdac-fceb-459a-8939-689da17de77e
Peer remove success
[okumar@localhost glusterd2]$ ./build/glustercli --endpoints=http://192.168.122.42:24007 peer list
+--------------------------------------+--------------+-----------------------+-----------------------+--------+------+
|                  ID                  |     NAME     |   CLIENT ADDRESSES    |    PEER ADDRESSES     | ONLINE | PID  |
+--------------------------------------+--------------+-----------------------+-----------------------+--------+------+
| 854e037e-da80-4ee0-82b8-9ecdb8fc13de | gd22.example | 127.0.0.1:24007       | 192.168.122.42:24008  | yes    | 2563 |
|                                      |              | 192.168.122.42:24007  |                       |        |      |
| a35e9c07-fc7c-45ac-a0a3-4e09869b30ca | gd20.example | 127.0.0.1:24007       | 192.168.122.253:24008 | yes    | 2586 |
|                                      |              | 192.168.122.253:24007 |                       |        |      |
+--------------------------------------+--------------+-----------------------+-----------------------+--------+------+
./build/glustercli --endpoints=http://192.168.122.42:24007 peer add 192.168.122.6
Peer add failed

Error: Request failed with HTTP Status code 500
failed to send join cluster request

# LOGS
INFO[2018-07-30 06:13:25.031666] handling new incoming join cluster request    remotecluster=21e282a0-398b-4726-88ab-af32b79f0237 remotepeer=854e037e-da80-4ee0-82b8-9ecdb8fc13de source="[peer-rpc-svc.go:45:peers.(*PeerService).Join]"
DEBU[2018-07-30 06:13:25.032392] all checks passed, joining new cluster        remotecluster=21e282a0-398b-4726-88ab-af32b79f0237 remotepeer=854e037e-da80-4ee0-82b8-9ecdb8fc13de source="[peer-rpc-svc.go:68:peers.(*PeerService).Join]"
DEBU[2018-07-30 06:13:25.032635] destroying current store                      source="[peer-rpc-svc.go:158:peers.ReconfigureStore]"
panic: close of closed channel

goroutine 225 [running]:
github.com/gluster/glusterd2/glusterd2/events.stopLivenessWatcher()
	/root/go/src/github.com/gluster/glusterd2/glusterd2/events/liveness.go:77 +0x30
github.com/gluster/glusterd2/glusterd2/events.Stop(0xc4206ab8d0, 0x1)
	/root/go/src/github.com/gluster/glusterd2/glusterd2/events/events.go:51 +0x22
github.com/gluster/glusterd2/glusterd2/commands/peers.ReconfigureStore(0xc4209fbf80, 0x0, 0x0)
	/root/go/src/github.com/gluster/glusterd2/glusterd2/commands/peers/peer-rpc-svc.go:161 +0x8b
github.com/gluster/glusterd2/glusterd2/commands/peers.(*PeerService).Join(0xc4208eb528, 0x110ed80, 0xc4209c59b0, 0xc4209c5a10, 0x0, 0x0, 0x0)
	/root/go/src/github.com/gluster/glusterd2/glusterd2/commands/peers/peer-rpc-svc.go:83 +0x3b6
github.com/gluster/glusterd2/glusterd2/commands/peers._PeerService_Join_Handler(0xedb200, 0xc4208eb528, 0x110ed80, 0xc4209c59b0, 0xc42009f360, 0x0, 0x0, 0x0, 0xc4207b6dd8, 0xc420040e00)
	/root/go/src/github.com/gluster/glusterd2/glusterd2/commands/peers/peer-rpc.pb.go:209 +0x241
github.com/gluster/glusterd2/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420154240, 0x1114f40, 0xc4208a0750, 0xc420120960, 0xc42088e420, 0x184f2a0, 0xc4209c5980, 0x0, 0x0)
	/root/go/src/github.com/gluster/glusterd2/vendor/google.golang.org/grpc/server.go:638 +0x8f3
github.com/gluster/glusterd2/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420154240, 0x1114f40, 0xc4208a0750, 0xc420120960, 0xc4209c5980)
	/root/go/src/github.com/gluster/glusterd2/vendor/google.golang.org/grpc/server.go:796 +0x1052
github.com/gluster/glusterd2/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420a06c20, 0xc420154240, 0x1114f40, 0xc4208a0750, 0xc420120960)
	/root/go/src/github.com/gluster/glusterd2/vendor/google.golang.org/grpc/server.go:449 +0x9f
created by github.com/gluster/glusterd2/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/root/go/src/github.com/gluster/glusterd2/vendor/google.golang.org/grpc/server.go:447 +0xa1

### PR DESCRIPTION
**Pull request by oshankkumar**
If liveness watcher has not been started then a call to stop liveness watcher was causing panic.
Root Cause : closing a closed chan will result in panic.

Closes #1092 
Closes #1012

Signed-off-by: Oshank Kumar <okumar@redhat.com>

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -23,3 +23,4 @@ endpoints.json
 generate-doc
 # Ignore vi backup files
 *~
+.idea
```
Comment (rishubhjain) [inline .gitignore]: Is this required in this PR?

File: glusterd2/events/liveness.go [hunk 2]
```diff
@@ -2,12 +2,12 @@ package events
 
 import (
 	"strings"
-	"sync"
 
 	"github.com/gluster/glusterd2/glusterd2/store"
 
 	"github.com/coreos/etcd/clientv3"
 	log "github.com/sirupsen/logrus"
+	"fmt"
```
Comment (rishubhjain) [inline glusterd2/events/liveness.go]: I think this should be grouped with standard library packages (strings) instead of 3rd party packages

File: glusterd2/events/liveness.go [hunk 3]
```diff
@@ -57,23 +56,34 @@ func (l *livenessWatcher) Watch() {
...
+			errc <- err
+			l.stopCh = nil
 			return
 		}
 	}
 }
 
+func (l *livenessWatcher) Stop() error {
+	if l.stopCh == nil {
+		return fmt.Errorf("livness watcher has not been started")
```
Comment (rishubhjain) [inline glusterd2/events/liveness.go]: TRIVIAL : Can we use errors.New() instead of fmt.Errorf() ?. As we have been using it throughout the gd2 code, it would look uniform.

File: .gitignore (hunk 1 above)
Comment (oshankkumar) [reply .gitignore]: No, .idea file created by IDE(IntelliJ), So just to ignore those file, I have added it in .gitignore

**Comment by Madhu-1** [comment]
retest this please

**Comment by Madhu-1** [comment]
ok to test

**Comment by prashanthpai** [comment]
@oshankkumar Please have a single commit. Rebasing against master should allow you to do that.

File: glusterd2/events/liveness.go [hunk 4]
```diff
@@ -16,23 +16,22 @@ const (
 )
 
 type livenessWatcher struct {
-	stopCh chan struct{}
-	wg     sync.WaitGroup
+	stopCh chan chan error
```
[the remark this answers is not in the document]
Comment (oshankkumar) [reply glusterd2/events/liveness.go]: chan of chan is generally a good idea to send notification back to the caller (https://talks.golang.org/2013/advconc.slide#26) and also we don't need waitgroup object as it also takes care of synchronization.

File: glusterd2/events/liveness.go [hunk 5]
```diff
@@ -16,23 +16,22 @@ const (
...
-	defer l.wg.Done()
-
+	var err error
 	wch := store.Store.Watch(store.Store.Ctx(), store.LivenessKeyPrefix,
 		clientv3.WithPrefix(), clientv3.WithKeysOnly())
 	for {
 		select {
 		case resp := <-wch:
 			if resp.Canceled {
+				l.stopCh = nil
```
[the remark this answers is not in the document]
Comment (oshankkumar) [reply glusterd2/events/liveness.go]: Stop() method ask a go-routine to exit by signalling it on a channel, if we do  l.Stop() and return from here then there won't be any channel available for recieving any event, So It  will go in a deadlock state.

File: glusterd2/events/liveness.go [hunk 6]
```diff
@@ -59,21 +57,35 @@ func (l *livenessWatcher) Watch() {
...
 	}
 }
 
+//Stop will stop the livenessWatcher if it is running and waits for
+//it to exit.
+func (l *livenessWatcher) Stop() error {
+	if l.stopCh == nil {
+		return errors.New("livness watcher has not been started")
+	}
+	stop := make(chan struct{})
```
[the remark this answers is not in the document]
Comment (oshankkumar) [reply glusterd2/events/liveness.go]: for synchronization, stop will wait until watch() returns

[the remark this answers is not in the document]
Comment (prashanthpai) [reply glusterd2/events/liveness.go]: Wouldn't the earlier waitgroup achieve the same ?

[the remark this answers is not in the document]
Comment (oshankkumar) [reply glusterd2/events/liveness.go]: okay, I will add waitgroup

**Comment by oshankkumar** [comment]
retest this please

File: .gitignore (hunk 1 above)
Comment (Madhu-1) [reply .gitignore]: this is specific to IDE, people use different development environment. I  think we don't need to add here

File: glusterd2/events/liveness.go [hunk 7]
```diff
@@ -65,15 +65,28 @@ func (l *livenessWatcher) Watch() {
...
 }
 
+//Stop will stop the livenessWatcher if it is running and waits for
+//it to exit.
+func (l *livenessWatcher) Stop() error {
+	if l.stopCh == nil {
+		return errors.New("livness watcher has not been started")
+	}
+	close(l.stopCh)
+	l.stopCh = nil
```
Comment (Madhu-1) [inline glusterd2/events/liveness.go]: question: why we need to assign ```nil``` to channel after closing it?

File: .gitignore (hunk 1 above)
Comment (prashanthpai) [reply .gitignore]: This is okay. Lot of projects do this. `*~` and `.swp` are vi/vim specific files. I've seen projects with Mac [specific](https://en.wikipedia.org/wiki/.DS_Store) file references in `.gitreview.`

File: glusterd2/events/liveness.go (hunk 7 above)
Comment (prashanthpai) [reply glusterd2/events/liveness.go]: To guard against `Stop()` being called again. Closing a closed channel causes panic

File: .gitignore (hunk 1 above)
Comment (prashanthpai) [reply .gitignore]: See https://github.com/heketi/heketi/blob/master/.gitignore too :)

File: glusterd2/events/liveness.go (hunk 7 above)
Comment (oshankkumar) [reply glusterd2/events/liveness.go]: if someone tries to close stopCh again then it will not result in panic, because a nil check is already given at the start of the method body.

Comment (Madhu-1) [reply glusterd2/events/liveness.go]: we can do 
```
read,ok := <- l.stopCh
if !ok{
return errors.New("livness watcher has not been started")
}
```

Comment (prashanthpai) [reply glusterd2/events/liveness.go]: The goal of stop channel isn't to pass values around. The logically valid operation at the sender end is to close it.
