### PR TITLE
 pmap: Synchronize port allocation across instances

### LINKED ISSUE #621: Port allocation happening twice while starting a daemon
During the daemon start process, port allocation is being done two times per daemon. This creates two entries in the portmap for each daemon and leads to the portmap entries not being cleared correctly when daemons are stopped.

### LINKED ISSUE #875: CI: Frequent spurious failure of TestVolume/Disperse test
```log
09:50:50     --- FAIL: TestVolume/Disperse (0.07s)
09:50:50     	assertions.go:247: 
                          
	Error Trace:	volume_ops_test.go:502
09:50:50     		
	Error:      	Expected nil, but got: &restclient.UnexpectedStatusError{msg:"Unexpected Status", expected:200, actual:500, resp:"Transaction step vol-start.StartBricks failed on peer 39f89674-1165-4d04-9842-0d2487a3720b with error: exit status 1\n"}
09:50:50     		
	Test:       	TestVolume/Disperse
09:50:50     		
	Messages:   	disperse volume start failed
```

### PR DESCRIPTION
**Pull request by prashanthpai**
This change synchronizes port allocation on a node/machine when multiple
glusterd2 instances are running (e2e tests). This solution is to be
treated as stopgap fix. A long term and more robust solution is to let
the bricks pick and bind on their own. This still doesn't rid the port allocation
of all the races but makes things better.

This change also ensures that when brick start operation is retried, a new
port is assigned.

Closes #621 
Closes #875

### CODE REVIEW

**Comment by prashanthpai** [comment]
```sh
$ glustercli peer list
+--------------------------------------+-------+------------------+-----------------+--------+
|                  ID                  | NAME  | CLIENT ADDRESSES | PEER ADDRESSES  | ONLINE |
+--------------------------------------+-------+------------------+-----------------+--------+
| de3d89d1-9b13-45cd-b3f2-b1c2c2ba0b3d | gd2-1 | 127.0.0.1:24007  | 127.0.0.1:24008 | yes    |
| edef80f1-74c3-4cf9-88f9-16b900fba166 | gd2-1 | 127.0.0.1:25007  | 127.0.0.1:25008 | yes    |
| fd79f774-b6c0-4564-a2fb-be6a936a7531 | gd2-1 | 127.0.0.1:23007  | 127.0.0.1:23008 | yes    |
+--------------------------------------+-------+------------------+-----------------+--------+

$ glustercli volume create test replica 3 \
> de3d89d1-9b13-45cd-b3f2-b1c2c2ba0b3d:/export/brick1 \
> edef80f1-74c3-4cf9-88f9-16b900fba166:/export/brick2 \
> fd79f774-b6c0-4564-a2fb-be6a936a7531:/export/brick3 \
> de3d89d1-9b13-45cd-b3f2-b1c2c2ba0b3d:/export/brick4 \
> edef80f1-74c3-4cf9-88f9-16b900fba166:/export/brick5 \
> fd79f774-b6c0-4564-a2fb-be6a936a7531:/export/brick6 \
> --force
test Volume created successfully
Volume ID:  19332ee0-0017-4cf1-85cf-2b3d3bae04f8

$ glustercli volume start test
Volume test started successfully
```

Locks held:

```sh
# lslocks
COMMAND           PID   TYPE SIZE MODE  M START END PATH
lvmetad           487  POSIX   4B WRITE 0     0   0 /run/lvmetad.pid
rpcbind           559  FLOCK   0B WRITE 0     0   0 /run/rpcbind/rpcbind.lock
crond             629  FLOCK   4B WRITE 0     0   0 /run/crond.pid
(unknown)          -1 OFDLCK      READ  0     0   0 /dev/pts...
(unknown)          -1 OFDLCK      READ  0     0   0 /dev/pts...
etcd            29462  FLOCK  16M WRITE 0     0   0 /tmp/default.etcd/member/snap/db
(unknown)          -1 OFDLCK      WRITE 0     0   0 /tmp...
(unknown)          -1 OFDLCK      WRITE 0     0   0 /tmp...
glusterd2       29519  FLOCK   0B WRITE 0     0   0 /run/glusterd2_pmap_port_49152.lock
glusterd2       29517  FLOCK   0B WRITE 0     0   0 /run/glusterd2_pmap_port_49153.lock
glusterd2       29519  FLOCK   0B WRITE 0     0   0 /run/glusterd2_pmap_port_49155.lock
glusterd2       29517  FLOCK   0B WRITE 0     0   0 /run/glusterd2_pmap_port_49156.lock
glusterd2       29518  FLOCK   0B WRITE 0     0   0 /run/glusterd2_pmap_port_49157.lock
(unknown)          -1 OFDLCK      READ  0     0   0 /dev/pts...
(unknown)          -1 OFDLCK      READ  0     0   0 /dev/pts...
glusterd2       29518  FLOCK   0B WRITE 0     0   0 /run/glusterd2_pmap_port_49154.lock
```

Logs:

```log
DEBU[2018-06-19 12:24:44.517268] Obtained lock on pmap port lock file.         lock-file=/var/run/glusterd2_pmap_port_49153.lock source="[pmap.go:97:pmap.(*registryType).TryPortLock]"
DEBU[2018-06-19 12:24:44.517355] Failed to obtain lock on pmap port lock file.  lock-file=/var/run/glusterd2_pmap_port_49154.lock source="[pmap.go:101:pmap.(*registryType).TryPortLock]"
DEBU[2018-06-19 12:24:44.517376] Failed to obtain lock on pmap port lock file.  lock-file=/var/run/glusterd2_pmap_port_49155.lock source="[pmap.go:101:pmap.(*registryType).TryPortLock]"
DEBU[2018-06-19 12:24:44.517390] Failed to obtain lock on pmap port lock file.  lock-file=/var/run/glusterd2_pmap_port_49156.lock source="[pmap.go:101:pmap.(*registryType).TryPortLock]"
DEBU[2018-06-19 12:24:44.517485] Obtained lock on pmap port lock file.         lock-file=/var/run/glusterd2_pmap_port_49157.lock source="[pmap.go:97:pmap.(*registryType).TryPortLock]"
```

**Comment by prashanthpai** [comment]
retest this please

**Comment by prashanthpai** [comment]
retest this please

File: glusterd2/pmap/pmap.go [hunk 1]
```diff
@@ -65,6 +70,56 @@ func (r *registryType) MarshalJSON() ([]byte, error) {
...
+		r.portLockFds[port] = fd
+		log.WithField("lock-file", portLockFile).Debug(
+			"Obtained lock on pmap port lock file.")
+		return true
+	case syscall.EWOULDBLOCK:
+		log.WithField("lock-file", portLockFile).Debug(
+			"Failed to obtain lock on pmap port lock file.")
+	}
+
+	syscall.Close(fd)
```
Comment (Madhu-1) [inline glusterd2/pmap/pmap.go]: just a question, do we need to delete the portLockFile in case of error?

Comment (prashanthpai) [reply glusterd2/pmap/pmap.go]: It's left out intentionally to avoid races. An unlink from one instance can happen after open from another. Its okay to have stale and harmless lock files than breaking locks.
