### PR TITLE
Prevent reusing bricks belonging to different volume

### LINKED ISSUE #931: Re-using active brick paths for another volume must be disallowed
**steps to reproduce issues**

1)create 2 volumes with same bricks
2)start 2 volumes
3)check glustercli volume status 

```
[root@dhcp42-235 ~]# cli volume status
Volume : test1
+--------------------------------------+----------------------------------+---------------------------------------------------------------------+--------+------+-------+
|               BRICK ID               |               HOST               |                                PATH                                 | ONLINE | PORT |  PID  |
+--------------------------------------+----------------------------------+---------------------------------------------------------------------+--------+------+-------+
| 870e7c7e-0452-405c-bd82-24df5f5dac6e | 10.70.42.235                     | /export/brick3/data/abc/123/12345/asdfasdf                          | true   |    0 |  4062 |
| d4039176-f3fc-4efe-b760-580e0c87a766 | dhcp43-75.lab.eng.blr.redhat.com | /export/brick4/data/xyz/123213213/sadfasdf                          | true   |    0 | 29984 |
| ed07870f-2bc0-46a9-b864-d1db08a5aa4a | 10.70.42.235                     | /export/brick1/data/safdsdfsadf/sadfsadfasdf/sdafsadf               | true   |    0 |  4040 |
| 266dd166-e469-4b4b-8e4f-a502b16f539e | dhcp43-75.lab.eng.blr.redhat.com | /export/brick2/data/sadfasdf/sadfsadfas/sadfdsafda/safdasd/sadfasdf | true   |    0 | 29962 |
+--------------------------------------+----------------------------------+---------------------------------------------------------------------+--------+------+-------+
Volume : test11
+--------------------------------------+----------------------------------+---------------------------------------------------------------------+--------+------+-------+
|               BRICK ID               |               HOST               |                                PATH                                 | ONLINE | PORT |  PID  |
+--------------------------------------+----------------------------------+---------------------------------------------------------------------+--------+------+-------+
| a020ae0a-032c-43c2-b09b-c15aafcc943a | 10.70.42.235                     | /export/brick1/data/safdsdfsadf/sadfsadfasdf/sdafsadf               | true   |    0 |  4040 |
| 78143001-3fe2-402d-8e2a-4ca7ac516e60 | dhcp43-75.lab.eng.blr.redhat.com | /export/brick2/data/sadfasdf/sadfsadfas/sadfdsafda/safdasd/sadfasdf | true   |    0 | 29962 |
| 457b505f-7f71-440b-a458-97797c766908 | 10.70.42.235                     | /export/brick3/data/abc/123/12345/asdfasdf                          | true   |    0 |  4062 |
| d4692d53-6e88-442c-96b8-9c45323de496 | dhcp43-75.lab.eng.blr.redhat.com | /export/brick4/data/xyz/123213213/sadfasdf                          | true   |    0 | 29984 |
+--------------------------------------+----------------------------------+---------------------------------------------------------------------+--------+------+-------+

```

**Expected Result:**

Brick ports should not be empty

**Failed to get volume status for same senario**

```
curl http://10.70.42.235:24007/v1/volumes/test1/status |python -m json.tool
  {
    "errors": [
        {
            "code": 1,
            "message": "Failed to get Volume size info"
        }
    ]
}

```

### PR DESCRIPTION
**Pull request by prashanthpai**
During volume create and volume expand, when `--force` or `--reuse-bricks` is
used, specifying a brick used by a different volume was being allowed. Bricks
belonging to a different active volume shouldn't be reused in any case.

This is enforced by:
* Checking volume id xattr on proposed brick path against volume id of other all
  available volumes.
* Checking if proposed brick path is a nested subdir of another active brick on
  the peer.

Closes #931 
Signed-off-by: Prashanth Pai <ppai@redhat.com>

### CODE REVIEW

File: glusterd2/brick/validation.go [hunk 1]
```diff
@@ -9,18 +9,20 @@ import (
 	"syscall"
 
 	"github.com/gluster/glusterd2/pkg/errors"
+	"github.com/pborman/uuid"
```
Comment (Madhu-1) [inline glusterd2/brick/validation.go]: need to add a new line.

File: glusterd2/brick/validation.go [hunk 2]
```diff
@@ -109,7 +111,9 @@ func validateXattrSupport(brickPath string) error {
 	return unix.Setxattr(brickPath, testXattrKey, []byte("payload"), 0)
 }
 
-func validateBrickInUse(brickPath string) error {
+// validateBrickWasUsed checks if the path was ever used a brick for a volume
+// by checking if the path has certain glusterfs specific xattrs
+func validateBrickWasUsed(brickPath string) error {
```
Comment (Madhu-1) [inline glusterd2/brick/validation.go]: question:
In which use case this function will be used if check for brick in use is mandatory?

Comment (prashanthpai) [reply glusterd2/brick/validation.go]: Use case: if you create a volume and then delete it, the xattr on the brick path isn't removed. When you try to create another volume from bricks of previously deleted volume, that check will be useful.

File: glusterd2/brick/validation.go (hunk 1 above)
Comment (prashanthpai) [reply glusterd2/brick/validation.go]: done

File: glusterd2/brick/validation.go (hunk 2 above)
Comment (Madhu-1) [reply glusterd2/brick/validation.go]: if we delete volume. don't we need to delete brick path also?

Comment (prashanthpai) [reply glusterd2/brick/validation.go]: > if we delete volume. don't we need to delete brick path also?

No we don't. Deleting the volume doesn't delete the data present in it. It also doesn't remove xattr present on brick path to prevent users accidentally reusing it without warning

Comment (Madhu-1) [reply glusterd2/brick/validation.go]: if this is the behavior in gd1, then its okay to have this.
