### PR TITLE
e2e: Fix temp dirs used by tests

### LINKED ISSUE #878: e2e: Cleanup temporary dir structure
The e2e tests create workdir inside workdir:

```
├── gd2_func_test
│   ├── TestVolume
│   │   ├── Expand
│   │   │   ├── 1
│   │   │   ├── 2
│   │   │   ├── 3
│   │   │   └── 4
│   │   └── VolumeFlags
│   │       ├── 1
│   │       ├── 2
│   │       ├── 3
│   │       └── 4
│   ├── TestVolume331630273 [error opening dir]
│   ├── w1
│   │   ├── log
│   │   │   ├── events.log
│   │   │   ├── glusterd2.log
│   │   │   ├── glusterfs
│   │   │   │   └── bricks
│   │   │   └── store
│   │   │       ├── elastic.log
│   │   │       └── etcd.log
│   │   ├── run
│   │   │   └── gluster
│   │   └── w1
│   │       ├── hooks
│   │       │   ├── add-brick
│   │       │   │   └── post
│   │       │   ├── create
│   │       │   │   └── post
│   │       │   ├── delete
│   │       │   │   └── post
│   │       │   ├── remove-brick
│   │       │   │   └── post
│   │       │   ├── reset
│   │       │   │   └── post
│   │       │   ├── set
│   │       │   │   └── post
│   │       │   ├── start
│   │       │   │   └── post
│   │       │   └── stop
│   │       │       └── post
│   │       ├── store [error opening dir]
│   │       ├── store.toml
│   │       └── uuid.toml
│   └── w2
│       ├── log
│       │   ├── events.log
│       │   ├── glusterd2.log
│       │   ├── glusterfs
│       │   │   └── bricks
│       │   │       ├── tmp-gd2_func_test-TestVolume331630273-brick329412434.log
│       │   │       ├── tmp-gd2_func_test-TestVolume331630273-brick472446853.log
│       │   │       ├── tmp-gd2_func_test-TestVolume331630273-brick629094043.log
│       │   │       ├── tmp-gd2_func_test-TestVolume-Expand-2.log
│       │   │       └── tmp-gd2_func_test-TestVolume-Expand-4.log
│       │   └── store
│       │       ├── elastic.log
│       │       └── etcd.log
│       ├── run
│       │   └── gluster
│       │       ├── 19463b09e2aedcad.socket
│       │       ├── 2e4ce57cea14542b.socket
│       │       ├── 6a73c48f94d2cf29.socket
│       │       ├── 6c05ce22-abfd-466d-9126-1a2aadafe608-tmp-gd2_func_test-TestVolume331630273-brick329412434.pid
│       │       ├── 6c05ce22-abfd-466d-9126-1a2aadafe608-tmp-gd2_func_test-TestVolume331630273-brick472446853.pid
│       │       ├── 6c05ce22-abfd-466d-9126-1a2aadafe608-tmp-gd2_func_test-TestVolume331630273-brick629094043.pid
│       │       ├── 6c05ce22-abfd-466d-9126-1a2aadafe608-tmp-gd2_func_test-TestVolume-Expand-2.pid
│       │       ├── 6c05ce22-abfd-466d-9126-1a2aadafe608-tmp-gd2_func_test-TestVolume-Expand-4.pid
│       │       ├── ce77c135579cb6dd.socket
│       │       ├── d8c3667b5256b414.socket
│       │       └── glusterd2.pid
│       └── w2
│           ├── hooks
│           │   ├── add-brick
│           │   │   └── post
│           │   ├── create
│           │   │   └── post
│           │   ├── delete
│           │   │   └── post
│           │   ├── remove-brick
│           │   │   └── post
│           │   ├── reset
│           │   │   └── post
│           │   ├── set
│           │   │   └── post
│           │   ├── start
│           │   │   └── post
│           │   └── stop
│           │       └── post
│           ├── store [error opening dir]
│           ├── store.toml
│           └── uuid.toml
```

### PR DESCRIPTION
**Pull request by prashanthpai**
The `localstatedir` from config file contained relative path which was
not being converted to absolute path before passing as command line
argument to glusterd2. This caused localstatedirs of different glusterd2
instances to be nested under one another. 

Closes #878 

Other minor fixes/cleanups:
* Ensure all tests use isolated temp dirs based on the name of the test
* Remove duplicate call to cleanupAllGlusterPvs()
* Unexport `UpdateDirs()` as it was is only used internally.

### CODE REVIEW

File: e2e/utils_test.go [hunk 1]
```diff
@@ -41,7 +42,7 @@ func (g *gdProcess) Stop() error {
 	return g.Cmd.Process.Kill()
 }
 
-func (g *gdProcess) UpdateDirs() {
+func (g *gdProcess) updateDirs() {
```
Comment (phlogistonjohn) [inline e2e/utils_test.go]: In my perfect world unexporting UpdateDirs would have been a separate commit, but that's mostly just a nitpick.
