### PR TITLE
Fix test in TestIsETCDStartNeeded

### LINKED ISSUE #80: Fix test in TestIsETCDStartNeeded

### PR DESCRIPTION
**Pull request by atinmu**
Kill() call should followed by Wait() before restarting any process

Closes #80

Signed-off-by: Atin Mukherjee <amukherj@redhat.com>

### CODE REVIEW

**Comment by atinmu** [comment]
Interestingly the culprit test passes in my dev environment, will further analyse the reason of the failure.

File: etcdmgmt/etcd-mgmt.go [hunk 1]
```diff
@@ -142,9 +143,20 @@ func isETCDStartNeeded() (bool, int) {
 			start = true
 			return start, pid
 		}
-
 		if exist := utils.CheckProcessExist(pid); exist == true {
-			start = false
+			hostname, err := os.Hostname()
+			if err != nil {
+				log.Fatal("Could not able to get hostname")
```
Comment (gaurav36) [inline etcdmgmt/etcd-mgmt.go]: don't you need to return something here. as log.Fatal does not return.

Comment (atinmu) [inline etcdmgmt/etcd-mgmt.go]: This is exactly what I commented in your patch that you would not need to return. log.Fatal does an exit() which means the entire application will terminate.

File: etcdmgmt/etcd-mgmt.go [hunk 2]
```diff
@@ -142,9 +143,20 @@ func isETCDStartNeeded() (bool, int) {
...
+			}
+			listenClientUrls := "http://" + hostname + ":2379"
+			_, err = http.Get(listenClientUrls + "/health")
+			if err != nil {
+				log.WithField("err", err).Error("etcd health check failed")
```
Comment (gaurav36) [inline etcdmgmt/etcd-mgmt.go]: we can have better log message something like "health of etcd is not good"

File: etcdmgmt/etcd-mgmt_test.go [hunk 3]
```diff
@@ -4,11 +4,39 @@ import (
...
+
+	log "github.com/Sirupsen/logrus"
 	heketitests "github.com/heketi/tests"
 )
 
+func formETCDCommand() *exec.Cmd {
+	hostname, err := os.Hostname()
+	if err != nil {
+		log.Fatal("Could not able to get hostname")
+		return nil
```
Comment (gaurav36) [inline etcdmgmt/etcd-mgmt_test.go]: using log.Fatal will not return here

File: etcdmgmt/etcd-mgmt.go (hunk 2 above)
Comment (atinmu) [inline etcdmgmt/etcd-mgmt.go]: How do they differ?

File: etcdmgmt/etcd-mgmt_test.go (hunk 3 above)
Comment (atinmu) [inline etcdmgmt/etcd-mgmt_test.go]: Will fix it

File: etcdmgmt/etcd-mgmt_test.go [hunk 4]
```diff
@@ -20,10 +48,11 @@ func TestStartETCD(t *testing.T) {
 	etcdCtx, err := StartETCD()
 	tests.Assert(t, err == nil)
 	etcdCtx.Kill()
+	etcdCtx.Wait()
 }
 
 func TestWriteETCDPidFile(t *testing.T) {
-	cmd := exec.Command("etcd")
+	cmd := formETCDCommand()
```
Comment (gaurav36) [inline etcdmgmt/etcd-mgmt_test.go]: after this you should also check whether cmd command is properly formed or its giving error.

File: etcdmgmt/etcd-mgmt_test.go [hunk 5]
```diff
@@ -33,33 +62,33 @@ func TestWriteETCDPidFile(t *testing.T) {
 	defer heketitests.Patch(&etcdPidFile, "/a/b/c/d/etcd.pid").Restore()
 	tests.Assert(t, writeETCDPidFile(cmd.Process.Pid) != nil)
 	cmd.Process.Kill()
+	cmd.Process.Wait()
```
Comment (gaurav36) [inline etcdmgmt/etcd-mgmt_test.go]: error handling of wait ?

File: etcdmgmt/etcd-mgmt_test.go [hunk 6]
```diff
@@ -33,33 +62,33 @@ func TestWriteETCDPidFile(t *testing.T) {
...
 }
 
 func TestIsETCDStartNeeded(t *testing.T) {
 	// check once etcd process is running isETCDStartNeeded returns false
 	os.Remove(etcdPidFile)
-	cmd := exec.Command("etcd")
+	cmd := formETCDCommand()
```
Comment (gaurav36) [inline etcdmgmt/etcd-mgmt_test.go]: same comment apply here. you should check return value of formETCDCommand.

File: etcdmgmt/etcd-mgmt_test.go (hunk 5 above)
Comment (atinmu) [inline etcdmgmt/etcd-mgmt_test.go]: I intentionally don't want to handle here as they will be duplicated.

File: etcdmgmt/etcd-mgmt_test.go [hunk 7]
```diff
@@ -33,33 +62,33 @@ func TestWriteETCDPidFile(t *testing.T) {
...
 	err := cmd.Start()
 	tests.Assert(t, err == nil)
 	err = writeETCDPidFile(cmd.Process.Pid)
 	tests.Assert(t, err == nil)
+	time.Sleep(15 * time.Second)
```
Comment (gaurav36) [inline etcdmgmt/etcd-mgmt_test.go]: why are you sleeping for 15 seconds? better to avoid sleep here

File: etcdmgmt/etcd-mgmt_test.go [hunk 8]
```diff
@@ -33,33 +62,33 @@ func TestWriteETCDPidFile(t *testing.T) {
...
+	tests.Assert(t, err == nil)
+	start, _ = isETCDStartNeeded()
+	tests.Assert(t, start == true)
 
 	// check if the pid file is missing then isETCDStartNeeded returns true
 	os.Remove(etcdPidFile)
 	start, _ = isETCDStartNeeded()
 	tests.Assert(t, start == true)
 	cmd.Process.Kill()
+	cmd.Process.Wait()
```
Comment (gaurav36) [inline etcdmgmt/etcd-mgmt_test.go]: error handling of wait ?

File: etcdmgmt/etcd-mgmt_test.go (hunk 4 above)
Comment (atinmu) [inline etcdmgmt/etcd-mgmt_test.go]: In formETCDCommand there is no code where an error would be returned, only one possibility is where os.Hostname() would fail but since we are calling log.Fatal the whole test would abort.

File: etcdmgmt/etcd-mgmt_test.go [hunk 9]
```diff
@@ -33,33 +62,33 @@ func TestWriteETCDPidFile(t *testing.T) {
...
+	_, err = cmd.Process.Wait()
+	tests.Assert(t, err == nil)
+	start, _ = isETCDStartNeeded()
+	tests.Assert(t, start == true)
 
 	// check if the pid file is missing then isETCDStartNeeded returns true
 	os.Remove(etcdPidFile)
 	start, _ = isETCDStartNeeded()
 	tests.Assert(t, start == true)
 	cmd.Process.Kill()
```
Comment (gaurav36) [inline etcdmgmt/etcd-mgmt_test.go]: error handling of kill.

File: etcdmgmt/etcd-mgmt_test.go (hunk 7 above)
Comment (atinmu) [inline etcdmgmt/etcd-mgmt_test.go]: We'd need to give some time window to etcd to get it settled. `checkHealth` function exactly does the same and the max time out is 15 secs.

File: etcdmgmt/etcd-mgmt_test.go (hunk 8 above)
Comment (atinmu) [inline etcdmgmt/etcd-mgmt_test.go]: Not required

**Comment by gaurav36** [comment]
NLGTM

File: etcdmgmt/etcd-mgmt_test.go (hunk 9 above)
Comment (atinmu) [inline etcdmgmt/etcd-mgmt_test.go]: I will handle to error code of Kill() & Wait() in one place rather than multiple places to ensure no redundant tests are there.

File: etcdmgmt/etcd-mgmt_test.go (hunk 7 above)
Comment (gaurav36) [inline etcdmgmt/etcd-mgmt_test.go]: instead of waiting for 15 seconds better to check health here.

Comment (atinmu) [inline etcdmgmt/etcd-mgmt_test.go]: Will check that out, thanks!

File: etcdmgmt/etcd-mgmt_test.go (hunk 9 above)
Comment (gaurav36) [inline etcdmgmt/etcd-mgmt_test.go]: yeah, it's better to handle these error in one place for all review comments/uncomment code to remove duplicity

File: etcdmgmt/etcd-mgmt.go (hunk 2 above)
Comment (gaurav36) [inline etcdmgmt/etcd-mgmt.go]: better readability

File: etcdmgmt/etcd-mgmt_test.go (hunk 4 above)
Comment (gaurav36) [inline etcdmgmt/etcd-mgmt_test.go]: if that is the case then no need to check error here. this comment is valid only if we are getting error.

File: etcdmgmt/etcd-mgmt_test.go (hunk 5 above)
Comment (gaurav36) [inline etcdmgmt/etcd-mgmt_test.go]: yeah, better to handle these error in one place.

File: etcdmgmt/etcd-mgmt.go (hunk 2 above)
Comment (atinmu) [inline etcdmgmt/etcd-mgmt.go]: IMO, they are same :)

File: etcdmgmt/etcd-mgmt_test.go [hunk 10]
```diff
@@ -6,9 +6,35 @@ import (
...
+
+	etcdCmd := exec.Command("etcd",
+		"-listen-client-urls", listenClientUrls,
+		"-advertise-client-urls", advClientUrls,
+		"-listen-peer-urls", listenPeerUrls,
+		"-initial-advertise-peer-urls", initialAdvPeerUrls,
+		"--initial-cluster", "default="+listenPeerUrls)
+
+	return etcdCmd
+}
```
Comment (gaurav36) [inline etcdmgmt/etcd-mgmt_test.go]: formETCD Command no longer needed with merging of #77 .

**Comment by gaurav36** [comment]
I am suppose to give comment on this patch. you have merged this patch.

**Comment by atinmu** [comment]
@gaurav36 : Apologies for not waiting, feel free to raise issue!

File: etcdmgmt/etcd-mgmt_test.go (hunk 10 above)
Comment (atinmu) [inline etcdmgmt/etcd-mgmt_test.go]: Will remove it (if possible) in a different PR
